# Generated by Django 2.1.7 on 2019-03-29 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatura',
            old_name='client',
            new_name='Client',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='data',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='fatura',
            name='Data',
            field=models.DateField(default=datetime.datetime(2019, 3, 29, 0, 23, 38, 322138, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='fatura',
            name='Descricao',
            field=models.TextField(default='Descrição da fatura'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='Valor',
            field=models.TextField(default='0,0€'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='Vendedor',
            field=models.TextField(default='EDP'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='imagemUrl',
            field=models.TextField(default='pasta/nomeImagem.jpeg'),
        ),
    ]
