# Generated by Django 2.1.7 on 2019-03-29 11:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0003_auto_20190329_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='Client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='Data',
            field=models.DateField(default=datetime.datetime(2019, 3, 29, 11, 36, 22, 984139, tzinfo=utc)),
        ),
    ]
