# Generated by Django 2.1.7 on 2019-03-29 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0004_auto_20190329_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='Data',
            field=models.DateField(default=datetime.datetime(2019, 3, 29, 11, 39, 23, 329551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='imagemUrl',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
