# Generated by Django 2.1.7 on 2019-03-29 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0005_auto_20190329_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='Data',
            field=models.DateField(default=datetime.datetime(2019, 3, 29, 11, 42, 36, 673093, tzinfo=utc)),
        ),
    ]
