# Generated by Django 2.1.7 on 2019-03-29 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0006_auto_20190329_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='Data',
            field=models.DateField(default=datetime.datetime(2019, 3, 29, 11, 49, 28, 523065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='imagemUrl',
            field=models.ImageField(default='default.jpg', upload_to='imagens_faturas'),
        ),
    ]
