# Generated by Django 2.1.7 on 2019-03-30 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0010_auto_20190330_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='Data',
            field=models.DateField(default=datetime.datetime(2019, 3, 30, 11, 20, 42, 555172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='Descricao',
            field=models.TextField(default='Descrição da fatura', max_length=200),
        ),
    ]
